/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.15.5.0 (NJsonSchema v10.6.6.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming



export interface AppDetailDto {
    id?: number;
    name?: string | null;
    appKey?: string | null;
    versionNumber?: number;
    classes?: ClassDetailDto[] | null;
}

export interface AppDto {
    id?: number;
    name?: string | null;
    appKey?: string | null;
    versionNumber?: number;
}

export interface ClassDetailDto {
    id?: number;
    code?: string | null;
    kind?: string | null;
    modifier?: string | null;
    name?: string | null;
    numberOfLines?: number;
    path?: string | null;
    usr?: string | null;
    versionNUmber?: number;
    methods?: MethodDetailDto[] | null;
    methodsCalls?: RelationshipDto[] | null;
    variables?: VariableDetailDto[] | null;
}

export interface ClassDto {
    id?: number;
    code?: string | null;
    kind?: string | null;
    modifier?: string | null;
    name?: string | null;
    numberOfLines?: number;
    path?: string | null;
    usr?: string | null;
    versionNUmber?: number;
}

export interface FileOpenedDto {
    projectId?: string | null;
    fileUri?: string | null;
}

export interface MethodDetailDto {
    id?: number;
    code?: string | null;
    cyclomaticComplexity?: number;
    endLine?: number;
    isConstructor?: boolean;
    isSetter?: boolean;
    isGetter?: boolean;
    kind?: string | null;
    maxNestingDepth?: number;
    name?: string | null;
    numberOfAccessedVariables?: number;
    numberOfCalledMethods?: number;
    numberOfCallers?: number;
    numberOfInstructors?: number;
    startLine?: number;
    type?: string | null;
    usr?: string | null;
    versionNumber?: number;
}

export interface MethodDto {
    id?: number;
    code?: string | null;
    cyclomaticComplexity?: number;
    endLine?: number;
    isConstructor?: boolean;
    isSetter?: boolean;
    isGetter?: boolean;
    kind?: string | null;
    maxNestingDepth?: number;
    name?: string | null;
    numberOfAccessedVariables?: number;
    numberOfCalledMethods?: number;
    numberOfCallers?: number;
    numberOfInstructors?: number;
    startLine?: number;
    type?: string | null;
    usr?: string | null;
    versionNumber?: number;
}

export interface PasswordLoginDto {
    username?: string | null;
    password?: string | null;
}

export interface ProjectDto {
    id?: string;
    userId?: string;
    projectId?: string | null;
}

export interface RegisterDto {
    username: string;
    password: string;
    email: string;
}

export interface RelationshipDto {
    start?: number;
    end?: number;
    type?: string | null;
}

export interface UserDto {
    id?: string;
    username?: string | null;
}

export interface UserTokenDto {
    user?: UserDto;
    token?: string | null;
}

export interface VariableDetailDto {
    id?: number;
    code?: string | null;
    name?: string | null;
    endLine?: number;
    kind?: string | null;
    startLine?: number;
    type?: string | null;
    usr?: string | null;
    versionNumber?: number;
}

export interface FileParameter {
    data: any;
    fileName: string;
}